"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const router = (0, express_1.Router)();
const product_controller_1 = require("../controllers/product.controller");
const product_controller_2 = require("../controllers/product.controller");
const product_controller_3 = require("../controllers/product.controller");
router.get('/products', product_controller_1.allProducts);
router.get('/products/:productId/:productName', product_controller_2.signleProduct);
router.post('/add/products', product_controller_3.addProduct);
exports.default = router;
